### ISSUE TITLE
[line breaks] One-line if/else statements without begin/end blocks

### ISSUE THREAD

**Issue by msfschaffner** [google/verible#103]
splitting out from #98.
 
is:
```systemverilog
if (cfg.if_mode == Host)
  driver = HOST_DRIVER_T::type_id::create("driver", this);
else
  driver = DEVICE_DRIVER_T::type_id::create("driver", this);
```
should:
```systemverilog
if (cfg.if_mode == Host)  driver = HOST_DRIVER_T::type_id::create("driver", this);
else                      driver = DEVICE_DRIVER_T::type_id::create("driver", this);
```

**Comment by msfschaffner** [comment]
b/146384260

**Comment by ldalek-antmicro** [comment]
Looks like related to #95

**Comment by fangism** [comment]
I think what @msfschaffner is emphasizing here is that single-statement clauses should be compacted onto the same line as `if ...` and `else` if they fit within the column limit.  #95 is about missing handling of `else`.

This may be helped by some of the comments about introducing CST nodes for `kIfClause` and `kElseClause` described here:

https://github.com/google/verible/pull/115#pullrequestreview-338247233

Introducing a level of partitioning will make it easier to apply the `kFitOnLineElseExpand` policy, and still provide opportunities to manipulate the partition tree.

Lastly, Michael's "should" example demonstrates statement alignment across clauses, which is not required to address at this time.

**Comment by ldalek-antmicro** [comment]
I've implemented what you've suggested in https://github.com/google/verible/pull/115#pullrequestreview-338247233 but also I've added
`kIfBody` and `kElseBody` for handling proper indentation in If-else statements, e.g.
```
      { (>>[<auto>]) @{16,0,1}
        { (>>[else if ( yy )]) }
        { (>>>>[<auto>]) @{16,0,1,1}
          { (>>>>[return 1 ;]) }
        }
      }
```
