### ISSUE TITLE
Forbid anonymous enums, require enums to be typedef'd.

### ISSUE THREAD

**Issue by fangism** [google/verible#16]
https://github.com/lowRISC/style-guides/blob/master/VerilogCodingStyle.md#enumerations

For this assignment, just check flag bare anonymous enums.

**Comment by fangism** [comment]
b/63778426

**Comment by fangism** [comment]
Suggestion: match enum declarations, and on match, search the context upwards to see if falls inside a typedef.

Since there is no name to highlight, in the violation report, you can point to either the `enum` keyword or the whole definition itself.

**Comment by rkapuscik** [comment]
If this is still free to take, I'd like to work on this.

**Comment by fangism** [comment]
Yes, available.  Thanks for volunteering, assigned to you.
