### ISSUE TITLE
Forbid parameter names starting with 'disable', suggest 'enable' instead.

### ISSUE THREAD

**Issue by fangism** [google/verible#162]
Our style guide now explicitly discourages naming parameters starting with 'disable'.
The guidance is to use positive sense naming, so starting with 'enable' is recommended.

Task:
* Check all parameter/localparameter declarations for this (even where those keywords are not required, e.g. module parameters inside `#()`).
* Make sure to cover case variations like `DiSaBlE`
* Cover class parameters, package parameters.
* Unit-tests for all of the above.

**Comment by fangism** [comment]
b/138755708

**Comment by fangism** [comment]
For the section reference (part of diagnostic issued), use the anchor: `#binary-parameters`

**Comment by tgorochowik** [comment]
@fangism should this be part of `ParameterNameStyleRule`?

I think it makes sense to create a separate rule for this (so one can be used without the other), but I guess it would require us to rename the currently existing rules to include what they actually check? `ParameterNameStyleRule` is quite broad.

Or maybe the prefix is not really a part of `style` and it could be just called `ParameterNamePrefixRule`?

**Comment by fangism** [comment]
Until we have more configurable rules (depending on #133 ), let's keep this as a separate rule to make it easy to disable.  We could call this one something like "PositiveMeaningParameterNames".
