### ISSUE TITLE
source code indexing, symbol/fact extraction, cross-reference linking

### ISSUE THREAD

**Issue by fangism** [google/verible#185]
Gist:
* extract symbol definitions and declarations and references
* establish use/definition links
* symbols would be properly scoped

Purpose:
* code navigation (IDEs)
* auto-completion
* all-of-the-above, but incremental, and operable on local workspace changes

Representation? any structure that is easily exportable/convertible to interfaces expected by other tools such as IDEs.
For example https://github.com/kythe/kythe is one platform for serving source code information and metadata.

**Comment by fangism** [comment]
@MinaToma work is ongoing at https://github.com/MinaToma/verible

**Comment by fangism** [comment]
@ivan444 FYI

**Comment by fangism** [comment]
b/163065644

**Comment by ivan444** [comment]
This is somewhat done. The indexing is working. The remaining tasks are covered with the finer grained bugs. This issue is not useful anymore.
