### ISSUE TITLE
 alternate rule for explicit parameter storage

### ISSUE THREAD

**Issue by msfschaffner** [google/verible#202]
While we do also require parameters/localparams to explicitly define a storage type in OpenTitan, there is one exception: "old-school" string parameters like this one
```systemverilog
parameter ARCHITECTURE = "FAST";
```
Unfortunately defining the storage type as `string` causes trouble with some tools. Hence, it would be great if we could enable a sort of "legacy" mode for this rule which allows string parameters.

**Comment by msfschaffner** [comment]
b/149605532

**Comment by fangism** [comment]
blocked by #133 

The way this would probably look (proposed) via command-line control is something like:

`--rules=explicit-parameter-storage=-string` meaning apply this rule except for when right-hand-side is a string-literal.

**Comment by msfschaffner** [comment]
Yes, sgtm.

**Comment by hzeller** [comment]
This is now a parameter to the `explicit-parameter-storage` rule.

With `--rules=explicit-parameter-storage=exempt_type:string`, this rule will not complain if the right-hand-side of the parameter assignment is a string literal.

**Comment by msfschaffner** [comment]
Great! Thanks for adding that feature.
