### ISSUE TITLE
[unpacked-dimensions-range-ordering] rule should exclude module array instances

### ISSUE THREAD

**Issue by fangism** [google/verible#276]
The following test case:

```systemverilog
module test (input logic [1:0] blah);
endmodule

module tb;
test test_i[3:0] (
  .blah (2'b0)
);
endmodule
```

is caught by `verilog_lint` as "[unpacked-dimensions-range-ordering]".
We would like to exempt module instance arrays from this check.

**Comment by fangism** [comment]
b/154451633

**Comment by fangism** [comment]
Running `verilog_syntax --printtree` on that input reveals that we can use the syntax tree context to refine the finding.  The tree dump includes:

```
...
          Node (tag: kGateInstanceRegisterVariableList) {
            Node (tag: kGateInstance) {
              (#SymbolIdentifier @65-71: "test_i")
              Node (tag: kUnpackedDimensions) {
                Node (tag: kDeclarationDimensions) {
                  Node (tag: kDimensionRange) {
                    (#'[' @71-72: "[")
                    Node (tag: kExpression) {
                      Node (tag: kNumber) {
                        (#TK_DecNumber @72-73: "3")
                      }
                    }
                    (#':' @73-74: ":")
                    Node (tag: kExpression) {
                      Node (tag: kNumber) {
                        (#TK_DecNumber @74-75: "0")
                      }
                    }
                    (#']' @75-76: "]")
                  }
                }
              }
...
```

So the check for exemption should use `kGateInstance`.

**Comment by Ciprian167** [comment]
If this is still free, I'd like to take a shot at it. I cannot self assign it yet.

**Comment by fangism** [comment]
Thank you for offering, let me know if you have any questions.

**Comment by Ciprian167** [comment]
I think this could be waived in UnpackedDimensionsRule::HandleSymbol by changing the return condition to something like:
``` C++
if (!ContextIsInsideUnpackedDimensions(context) || 
     context.IsInside(NodeEnum::kGateInstance)) return;
```
What do think?

**Comment by fangism** [comment]
> I think this could be waived in UnpackedDimensionsRule::HandleSymbol by changing the return condition to something like:
> 
> ```c++
> if (!ContextIsInsideUnpackedDimensions(context) || 
>      context.IsInside(NodeEnum::kGateInstance)) return;
> ```
> 
> What do think?

I think that might do.  Suggest building up some test cases to verify.
