### ISSUE TITLE
';' after `uvm_* statements is unwanted

### ISSUE THREAD

**Issue by fangism** [google/verible#281]
We've resolved to be consistent on this subject.

All `` `uvm_* `` _statements_, shall not be terminated with `;`.

Task:

* Examine the syntax tree difference between macro-call statements with vs. without `;` (use `verilog_syntax --printtree`)
* Identify all macro-call statements that start with `` `uvm_ `` in a new `SyntaxTreeLintRule` subclass.
* Check if they terminate with a `;`, and report them.
* Write unit-test test cases.

**Comment by fangism** [comment]
b/155128436

**Comment by svenka3** [comment]
As a regular user and reveiwer of UVM code, I would like to point out that, though this rule is a good one, many user environments violate this one consistently. It is so hard to educate them and trainers across the globe have given up on this one (Cliff Cumming's words at DVCon US 2020). Also I have heard one EDA vendor arguing it is still a legal SV syntax (A null or something). Also most of the simulators accept this extra ;

Hence, my suggestion would be not to add this rule - most violated one it shall become.

Regards
Srini

**Comment by fangism** [comment]
Hi there, this request came from a consensus reached by internal users, and doesn't necessarily mean it has to be imposed on everyone else -- just those who want it moving forward for consistency, and with less interest about fixing legacy code.  With ever-improving configurability in the style linter, you can have it your own way and opt-out.

**Comment by fangism** [comment]
Also tools never get exhausted trying to educate users.  :)

**Comment by Ciprian167** [comment]
@fangism If it's still free, I would like to take a look at it. Could you please assing it to me?
