### ISSUE TITLE
centos-6 and centos-7 releases fail due to missing devtoolset-6

### ISSUE THREAD

**Issue by hzeller** [google/verible#285]
Travis currently has issues compiling for these centos targets, thus all travis builds look like they failed (though the regular build and test is just fine)

https://travis-ci.org/github/google/verible/jobs/680765831#L1521
https://travis-ci.org/github/google/verible/jobs/680765832#L2054

These are referenced in https://github.com/google/verible/blob/master/Docker/docker-generate.sh - are there newer versions ?

**Comment by hzeller** [comment]
Tim, you might be able to quickly see what is going on.

**Comment by hzeller** [comment]
CentOS 6 and 7 are still consistently failing to build; if you're busy, I can have a look tonight @mithro

**Comment by mithro** [comment]
I won't be able to look at this until next week at the earliest. Feel free to take a look
