### ISSUE TITLE
Release build for Ubuntu 20.04 Focal Fossa

### ISSUE THREAD

**Issue by gareth8118** [google/verible#300]
I'm going to try building from scratch for now but this ticket is to formally request an Ubuntu build for the [recently released](https://wiki.ubuntu.com/FocalFossa/ReleaseSchedule) 20.04 LTS "Focal Fossa". Thanks!

**Comment by mithro** [comment]
I'm theory should be as simple as adding another set of lines at https://github.com/google/verible/blob/0b0011b50b7b9774b11d6e824ada0ff2f34ef6a4/.travis.yml#L54

Does someone want to give that a go?

**Comment by fangism** [comment]
Looks done.  Re-open if you think there's more work.
