### ISSUE TITLE
Support for comments in waiver files

### ISSUE THREAD

**Issue by imphil** [google/verible#341]
Waiver files for Verible lint (passed with `--waiver_files`) do not (seem to) support comments. Can that support be added, in line with the comment support in rules files, which was added in https://github.com/google/verible/issues/274?

Comments in waiver are essential to give a bit of motivation why a waiver is necessary (and to add a license header).

**Comment by fangism** [comment]
What style of comments would you like?  `#`?  `//`?

Would need to start by adding a comment token pattern here:

https://github.com/google/verible/blob/master/common/analysis/command_file.lex

and make sure it gets filtered out before reaching the parser.

**Comment by imphil** [comment]
I don't mind; `#` would be consistent with the rule config files (see  #274 / https://github.com/google/verible/commit/7d55b5b320b8d60d0a1a8924ea9f8fa02a50551d), so I'd opt for that.
