### ISSUE TITLE
Formatter: Indent parameter and port list with two spaces

### ISSUE THREAD

**Issue by imphil** [google/verible#348]
The style guide used in OpenTitan and Ibex requires two space indent for parameter and port lists; the formatter seems to prefer four spaces.

Docs:
* https://github.com/lowRISC/style-guides/blob/master/VerilogCodingStyle.md#basic-template
* https://github.com/lowRISC/style-guides/blob/master/VerilogCodingStyle.md#module-declaration

Actual

```systemverilog
module something #(
    parameter int Width = 1600
) (
    input clk
);
```

Expected

```systemverilog
module something #(
  parameter int Width = 1600
) (
  input clk
);
```

**Comment by fangism** [comment]
Duplicate of #40

**Comment by imphil** [comment]
I thought there must have been an issue for it, but didn't find it. Sorry, let's continue the discussion in #40.
