### ISSUE TITLE
index and serve navigable UI into Verible codebase

### ISSUE THREAD

**Issue by fangism** [google/verible#371]
Serving a searchable/indexed view of the Verible codebase would greatly aid developers.  

Options:

* Kythe, and run our own
* http://source.cloud.google.com
* Some github extension?

Ideally the index would be updated on every commit (even if releases ever decrease in frequency).

@mithro @hzeller I think we have someone working on the Kythe option.

**Comment by mithro** [comment]
@fangism - We should get it into codesearch (both external and internal). There is an internal to Google document on how we do that.

**Comment by fangism** [comment]
@MinaToma thanks for working on this
