### ISSUE TITLE
Recommend parentheses around certain expression patterns

### ISSUE THREAD

**Issue by fangism** [google/verible#383]
Though parsers and compilers know fully well the precedence of operators, humans can still benefit from extra parenthesis.

example:
https://github.com/lowRISC/style-guides/blob/master/VerilogCodingStyle.md#parentheses

Task: detect such situations (starting with the above ternary expression example) and report them

Suggest: subclassing a SyntaxTreeLintRule and for various expression types, looking downwards at its operands and comparing operators/precedences.  

Feel free to suggest more specific operator classes and cases.

**Comment by fangism** [comment]
b/159846534

**Comment by omarahmed1111** [comment]
@fangism Hello, I would like to work on this, could you assign me? Thanks

**Comment by fangism** [comment]
Thank you!.  I have some lint-rule development documentation here:
https://github.com/google/verible/blob/master/doc/style_lint.md

I suggest starting by proposing a concrete set of test cases, given the initial description.
Feel free to propose your solution for discussion.  We're here to help.

**Comment by fangism** [comment]
Thanks for working on this again.
I suggest we name this rule `"suggest-parentheses"` and the class `SuggestParenthesisRule`, and the topic anchor is named `"parentheses"`.

**Comment by fangism** [comment]
Just checking in, what's the current status of this PR?

**Comment by omarahmed1111** [comment]
Just need to add some tests for the helper functions and I will update it hopefully this week. Apologies for late updates as i have some issues the past weeks.
