### ISSUE TITLE
Kythe: add verification tests to Verible's CI

### ISSUE THREAD

**Issue by ivan444** [google/verible#395]
Prevent breakages of Kythe extraction logic by running the [verification tests](https://kythe.io/docs/kythe-verifier.html) as a part of Verible's continuous integration.

The initial set of Kythe verification tests is being added with PR #386.

Umbrella issue: #185

**Comment by MinaToma** [comment]
Re-opening because the tests aren't added to the CI yet.

**Comment by fangism** [comment]
co-assigning to @ivan444 to help with the starlark test rules.
