### ISSUE TITLE
Kythe: extract module instance parameters as children not as anchors

### ISSUE THREAD

**Issue by MinaToma** [google/verible#420]
Extraction of  `module_type m(a,b,c,d)` needs to change as `a,b,c,d` are now anchors and should be considered as children to be able to extract `module_type m(id1[id2]);`

**Comment by MinaToma** [comment]
@fangism I tried this example and it worked fine (I think using `wire` as an index isn't right but ignore it as `int` isn't extracted yet)

```
module simple(input a, output b);
endmodule

module with_array();

    wire a[1:0];
    wire x = 0, y = 1;

    simple sim(a[x], a[y]);

endmodule
```

**Comment by MinaToma** [comment]
Can the port be class member or some package member?

**Comment by fangism** [comment]
> @fangism I tried this example and it worked fine (I think using `wire` as an index isn't right but ignore it as `int` isn't extracted yet)
> 
> ```
> module simple(input a, output b);
> endmodule
> 
> module with_array();
> 
>     wire a[1:0];
>     wire x = 0, y = 1;
> 
>     simple sim(a[x], a[y]);
> 
> endmodule
> ```

That's ok, it should be able to tolerate what would otherwise fail semantically.  Source code validation is the responsibility of other tools.

**Comment by fangism** [comment]
> Can the port be class member or some package member?

I think so, if they are compile-time constant values.
