### ISSUE TITLE
[kythe] missing definition of formal parameter (module/interface/class)

### ISSUE THREAD

**Issue by fangism** [google/verible#485]
## Input test case

```systemverilog
interface core_ibex_instr_monitor_if #(
  parameter DATA_WIDTH = 32
) (
  input clk
);
  logic [DATA_WIDTH-1:0]  instr_id;
endinterface
```

## Describe what is wrong or missing

`DATA_WIDTH` is missing a definition anchor in the parameter list, and also a reference in the declaration of `instr_id`.

**Comment by MinaToma** [comment]
Note while solving this issue: check also extraction for `kPackedDimenstion` and `kUnPackedDimenstion` in different CST nodes.

**Comment by MinaToma** [comment]
Related to #394
