### ISSUE TITLE
[kythe] missing reference to formal type parameter in class declaration with extends

### ISSUE THREAD

**Issue by fangism** [google/verible#486]
## Input test case

```systemverilog
class uvm_sequence_item
endclass

class uvm_sequence #(parameter type T = int);
endclass

class core_base_seq #(type REQ = uvm_sequence_item) extends uvm_sequence#(REQ);
endclass
```

## Describe what is wrong or missing

1) In the declaration of `core_base_seq`, the `REQ` in `extends uvm_sequence#(REQ)` should reference the `REQ` formal type parameter.
1) `uvm_sequence_item` in `type REQ = uvm_sequence_item` (default) should reference the `class uvm_sequence_item` on line 1.

**Comment by MinaToma** [comment]
Related to #394.
