### ISSUE TITLE
[kythe] different objects' members with same name should beget distinct references

### ISSUE THREAD

**Issue by fangism** [google/verible#490]
## Input test case

Try to reduce the test down to a single demonstrative file.

```systemverilog
class c;
  irq_raise_seq                                 irq_raise_seq_h;
  irq_raise_single_seq                          irq_raise_single_seq_h;
  virtual task body();
    if (x) begin
      irq_raise_single_seq_h.num_of_iterations = 1;
    end
    if (y) begin
      irq_raise_seq_h.num_of_iterations = 1;
    end
  endtask
endclass
```

## Describe what is wrong or missing

The 2 occurrences of `num_of_iterations` emit the same reference, when in fact they belong to members of different types.

Possibly related to #483

**Comment by MinaToma** [comment]
The `num_of_iterations` now do not emit references as their definitions can't be found. 
So they do emit the same reference.
