### ISSUE TITLE
incorrect indentation of `initial begin...end` blocks with //comment

### ISSUE THREAD

**Issue by udinator** [google/verible#499]
**Test case**

```systemverilog
initial // clock generation
  begin
    clk = 0;
    forever begin
      #4ns clk = !clk;
    end
  end
```

**Actual output**

```systemverilog
initial // clock generation
    begin
  clk = 0;
  forever begin
    #4ns clk = !clk;
  end
end
```

**Expected or suggested output**

The formatter should not touch this input block at all as it is already formatted correctly.

```systemverilog
initial // clock generation
  begin
    clk = 0;
    forever begin
      #4ns clk = !clk;
    end
  end
```

Citations to published style guides would help.

**Comment by fangism** [comment]
b/169252975

**Comment by wtatarski** [comment]
@fangism  @udinator 
At this moment the actual output looks like this:
```
initial // clock generation
  begin
  clk = 0;
  forever begin
    #4ns clk = !clk;
  end
end
```
Do you think that additional indentation is required after `begin`?

**Comment by udinator** [comment]
Hi @wtatarski - I'd prefer that we keep the additional indentation after the `begin`.
