### ISSUE TITLE
Add an option to the obfuscator for preserving module interface names

### ISSUE THREAD

**Issue by hchsiao** [google/verible#530]
In our application, it would be useful to obfuscate everything except interface names (e.g. module name and port names) of an IP, as it can be less error-prone for customers when they integrate the IP into their design.

Seems like it could also be useful in other use cases, I will work on this ( #529 ) recently.
Features planned to implement include:
- Add `--preserve_interface` option to the obfuscator binary
- Several CST node/leaf finder functions needed to implement the option

Any help or comments are welcomed!

**Comment by fangism** [comment]
Nice idea!  Aside from regular `SymbolIdentifier`s, also consider macro-identifiers that might appear in public sections like module headers.
