### ISSUE TITLE
Require structs and unions to be typedef'd, never anonymous

### ISSUE THREAD

**Issue by fangism** [google/verible#54]
Similar to #16 report anonymous structs and unions as lint violations.  
You may choose to implement this as one or two rules.

Suggestion: match on struct declaration, and search context to see if it inside a typedef.

**Comment by fangism** [comment]
b/145245466

**Comment by rkapuscik** [comment]
If no work is going on here, I would like to take this as well. I suppose solution will be similar to #61.

**Comment by fangism** [comment]
Yes, thanks.  This is now yours.
