### ISSUE TITLE
[kythe] linkify anonymous struct/unions member references

### ISSUE THREAD

**Issue by fangism** [google/verible#545]
## Input test case

```systemverilog
function f;
  struct { int x; int y; } data;
  int sum = data.x + data.y;
endfunction
```

## Describe what is wrong or missing

`x` in `data.x` should point to the member inside the anonymous struct.  Likewise for `y`.

This is also plausible in ports:

```systemverilog
function f(struct { int x; int y; } data);
  int sum = data.x + data.y;
endfunction
```

**Comment by MinaToma** [comment]
Related to #540

**Comment by MinaToma** [comment]
Are the missing `()` in the first function intended?

**Comment by fangism** [comment]
> Are the missing `()` in the first function intended?

You may add them if you like.  It's syntactically legal either way.

```systemverilog
function int f();
  struct { int x; int y; } data;
  return data.x + data.y;
endfunction
```
