### ISSUE TITLE
travis-ci: builds time out

### ISSUE THREAD

**Issue by fangism** [google/verible#556]
Since kythe was added as a dependency, most travis-builds have been timing out.

First bad:
https://travis-ci.org/github/google/verible/jobs/739104819

Last good:
https://travis-ci.org/github/google/verible/builds/738921915
https://travis-ci.org/github/google/verible/builds/738413728

Things one could look into, to name a few:

* .github/travis/script.sh -- adding some time commands or timestamps
* bazel -j parallelization, already max'd?
* Maintaining a persistent bazel build cache from build-to-build (but also have a way to reset the cache, just-in-case)

**Comment by fangism** [comment]
b/171743791

**Comment by fangism** [comment]
@mithro anyone on AntMicro team available to help?

**Comment by fangism** [comment]
Most recent timeout: https://travis-ci.org/github/google/verible/builds/740056016

**Comment by mithro** [comment]
@kgugala - Can you get someone to look at this?

**Comment by kgugala** [comment]
@fangism can we migrate the CI to e.g. github actions? there is 6h time limit in actions

**Comment by fangism** [comment]
No objection from me.  (I am still interested if there are some easy speed-ups though.)

**Comment by mglb** [comment]
I've added timestamps to script.sh. Results: 
* Environment initialization takes < 1 min
* `bazel test` takes about 29 min
* `bazel build` runs until timeout.

See build log for more details: https://travis-ci.com/github/antmicro/verible/jobs/423717516

Running test and build in separate jobs solves the problem. Each job runs in parallel for 29 minutes: https://travis-ci.com/github/antmicro/verible/builds/197663893

**Comment by fangism** [comment]
Thanks, I commented in the PR: can we try matching the `-c opt` for both build and test, for the sake of caching?

**Comment by tgorochowik** [comment]
@fangism should we still migrate the CI to github actions? It probably makes sense to do that to avoid similar issues in the future.

**Comment by mithro** [comment]
@tgorochowik - Yes please move to GitHub Actions ASAP.

**Comment by fangism** [comment]
All former Travis-CI actions have been migrated to github actions.
