### ISSUE TITLE
Inconsistency in pure task

### ISSUE THREAD

**Issue by MinaToma** [google/verible#569]
**Describe the bug**

The CST of `pure tasks` should contain a `kTaskHeader` node.

**To Reproduce**

```systemverilog
class Base2;
   pure virtual task disp();
endclass
```

**Actual behavior:**
Current CST:
```
Node @1 (tag: kTaskPrototype) {
          Leaf @1 (#"task" @407-411: "task")
          Leaf @3 (#SymbolIdentifier @412-416: "disp")
          Node @4 (tag: kParenGroup) {
            Leaf @0 (#'(' @416-417: "(")
            Leaf @2 (#')' @417-418: ")")
          }
          Leaf @5 (#';' @418-419: ";")
        }
```

**Expected behavior**

Re-shape CST for pure tasks to have `kTaskHeader`.

**Comment by fangism** [comment]
Confirmed, thanks.

**Comment by MinaToma** [comment]
There is some inconsistency with normal task header:

CST for pure task header:
``
Node @1 (tag: kTaskPrototype) {
  Node @0 (tag: kTaskHeader) {
    Leaf @1 (#"task" @394-398: "task")
    Leaf @3 (#SymbolIdentifier @399-403: "disp")
    Node @4 (tag: kParenGroup) {
      Leaf @0 (#'(' @403-404: "(")
      Leaf @2 (#')' @404-405: ")")
    }
    Leaf @5 (#';' @405-406: ";")
  }
}
```

CST for tasks:
```
Node @0 (tag: kTaskHeader) {
  Node @0 (tag: kQualifierList) {
    Leaf @0 (#"virtual" @434-441: "virtual")
  }
  Leaf @1 (#"task" @442-446: "task")
  Node @3 (tag: kUnqualifiedId) {
    Leaf @0 (#SymbolIdentifier @447-451: "disp")
  }
  Node @4 (tag: kParenGroup) {
    Leaf @0 (#'(' @451-452: "(")
    Leaf @2 (#')' @452-453: ")")
  }
  Leaf @5 (#';' @453-454: ";")
}
```

`SymbolIdentifier` in pure task isn't wrapped inside a `kUnqualifiedId` node.

**Comment by fangism** [comment]
Fix underway.
