### ISSUE TITLE
Support for SV nettype 

### ISSUE THREAD

**Issue by msfschaffner** [google/verible#581]
**Summary**

The SV `nettype` keyword is currently not supported by Verible.
Since analog circuit models may sometimes contain this keyword, it would be nice if this was supported as well.

**Test cases and examples**

The more examples you provide, the easier it will be for someone to come along
and implement it.

```systemverilog
nettype real awire;
```

**Additional context**

See also https://verificationacademy.com/forums/systemverilog/difference-between-nettype-and-wire-logic for examples and more references.

**Comment by msfschaffner** [comment]
b/172677968

**Comment by msfschaffner** [comment]
CC @arnonsha

**Comment by msfschaffner** [comment]
This came up in https://github.com/lowRISC/opentitan/pull/3952#discussion_r517198761

**Comment by fangism** [comment]
This is LRM-2017, section 6.6.7 User-defined nettypes.
