### ISSUE TITLE
Data type check in function arguments

### ISSUE THREAD

**Issue by svenka3** [google/verible#617]
**Summary**
Recently found this on OpenTitan, see:

https://github.com/lowRISC/opentitan/issues/4355#issuecomment-736782490

Wondering if this will be caught in Verible using existing rules. 

**Test cases and examples**

Is there a running version of OpenTitan in Verible that I can try out at my end? 

Code snippet is available on https://github.com/lowRISC/opentitan/issues/4355#issuecomment-736782490

Will be happy to extract a small test should that be necessary.

**Comment by fangism** [comment]
Verible is a still quite a ways off from being able to do semantics that require elaboration.  Type/width checking will have to come after symbol-binding (we have a small start in the way of source code indexing), and preprocessing.  I believe Verilator comes with many semantic linting capabilities.

**Comment by svenka3** [comment]
OK, will close this ticket.

**Comment by mithro** [comment]
https://github.com/alainmarcel/Surelog might be able to do what you want.
