### ISSUE TITLE
Releases seem to be broken

### ISSUE THREAD

**Issue by mithro** [google/verible#619]
It seems like the uploading github releases is not working.

**Comment by fangism** [comment]
Is this related to the kokoro-kythe faillures?

**Comment by mithro** [comment]
I think is caused by the Travis -> GitHub actions move...

**Comment by mithro** [comment]
All the released files seem to be uploading to the latest release -- https://github.com/google/verible/releases

**Comment by mithro** [comment]
![Screenshot from 2020-12-04 11-16-12](https://user-images.githubusercontent.com/21212/101205141-286dbb00-3622-11eb-960a-6ab5e7e777b1.png)

**Comment by mithro** [comment]
* https://github.com/marketplace/actions/create-a-release
 * https://github.com/marketplace/actions/upload-a-release-asset

**Comment by mithro** [comment]
We should probably be using one of the two more standard github actions for uploading a the releases. I'm unsure why we are using https://github.com/svenstaro/upload-release-action

https://github.com/google/verible/blob/b74ff0df4ae9e9d0457cefaa3e6774f4b1251d6f/.github/workflows/verible-ci.yml#L85-L93

**Comment by mithro** [comment]
The issue is https://github.com/google/verible/blob/b74ff0df4ae9e9d0457cefaa3e6774f4b1251d6f/.github/workflows/verible-ci.yml#L91

`${{ github.ref }}` converts to `master` rather than the newly generated tag version.

**Comment by umarcor** [comment]
Is the purpose the following?

On sucess:

- Create a git tag.
- Push the tag to the repo.
- Create a release pointing to that tag.
- Upload some assets to the release.

**Comment by mithro** [comment]
Pretty much.

What I don't understand is how the `$TRAVIS_TAG` value ended up being `# Create a tag of form v0.0-183-gdf2b162-20191112132344`

**Comment by mithro** [comment]
`git-describe` would produce the `v0.0-183-gdf2b162` part and the number comes from when the travis job was scheduled...

**Comment by mithro** [comment]
Looking at all the releases listed, as far as I can tell the date part has never worked.....

**Comment by mithro** [comment]
Looks like after #625 was fixed, this change started working! https://github.com/google/verible/releases
![Screenshot from 2020-12-08 12-34-57](https://user-images.githubusercontent.com/21212/101538347-d1355680-3951-11eb-91a1-8e7f6f64236b.png)

**Comment by umarcor** [comment]
@mithro, remember to remove tag 'master' and that release with 142 assets.
