### ISSUE TITLE
CI build support for Mac OS X / Darwin

### ISSUE THREAD

**Issue by mithro** [google/verible#64]
Travis [supports CI on Windows and Mac](https://docs.travis-ci.com/user/multi-os/). You can also use clang / gcc on these systems and I believe bazel also supports these systems? Do we want to support these OSs?

**Comment by fangism** [comment]
I would like to support Mac OS (darwin), because that is my personal development platform.

**Comment by hzeller** [comment]
Passing on to David as he has a Mac to test.

**Comment by hzeller** [comment]
Fixed with #757
