### ISSUE TITLE
Add a way to check c++ formatting

### ISSUE THREAD

**Issue by tgorochowik** [google/verible#70]
Preferably the CI should check it for each PR + it should be possible to trigger formatting locally.

CC @hzeller

**Comment by kgugala** [comment]
it can run `make format` from #71 and check if there were any changes in the code after the formatter run

**Comment by fangism** [comment]
IMHO, this should be done as a git command hook, much like the way `git clang-format` is done.
No Makefile targets needed.

**Comment by tgorochowik** [comment]
The CI now does this:
https://github.com/google/verible/blob/65bda400fd1adea349c240e6e98bbf8383d67394/.github/workflows/verible-ci.yml#L21-L42

closing.
