### ISSUE TITLE
Move to use C++17 and with it, embrace std::filesystem

### ISSUE THREAD

**Issue by hzeller** [google/verible#765]
- [ ] Evaluate if we can move to c++17, by checking all the (sometimes pretty old) distributions we support when building.  **No** : all compilers can do c++17, but not all of them provide the `<filesystem>` header yet.
- [x] Are there inconveniences that we need to factor in ? For instance do we need to tell users to add `--cxxopts=-std=c++17`, or is that the default already with using a current bazel (4.0.0). If it is the default with 4.0.0 (current version bazel) but not 3.7 which we use for CI currently, then we might first need to await the Kythe dependency reduction (which now pins us on 3.7) (_inconveniences already managed in `.bazelrc`_; Independent, using Bazel 4.0.0 now #794  )
  - [x] Adapt CI to use C++17 enabled compiler if not already _already happening, but release docker gcc's can't deal all with `<filesystem>`_
  - [x] Add possible documentation updates if special `cxxopts` are needed when building (hopefully not). _not needed_
- [x] Replace all unix-specific code with std::filesystem (Done in _#789_, but currently only enabled for Windows)
   - [x] There is at least one function [`UpwardFileSearch()`](https://github.com/google/verible/blob/6ef4938d0a800b93ebf9fa7fdf692c4ed06c0471/common/util/file_util.h#L56-L60) that needs a unit test first. Possibly more.
   - [x] To use `std::filesystem` in the past, there was the inconvenience to have to add `-lstdc++fs`. This might probably be possible to add to the `copts` in the BUILD file, but we need to make sure this works on all `gcc` and `clang` a well as on all used compiler versions of these (because it seems to be impossible in bazel to change `copts` in BUILD files depending on toolchain used).  _for all gcc versions that do support `<filesystem>` nothing has to be added to link options_

This issue will probably the aggregation point for multiple submits until we have replaced

**Comment by hzeller** [comment]
In #789 an implementation to used `std::filesystem` has been added, but _only_ enabled for Windows right now as the release builds (in [`releasing/`](https://github.com/google/verible/tree/master/releasing)) sometimes run on such old platforms that they don't have new enough compilers yet.

TODO: install the necessary compilers there (backports?) and always [enable std::filesystem]( https://github.com/google/verible/blob/495dda72923d1a13422a6f3a3fd131ed3b1fff37/common/util/file_util.cc#L44) for all platforms.

Once that is done, the legacy implementation can be removed.

**Comment by hzeller** [comment]
Assigning to Tim to figure out the release compiler situation.

**Comment by mithro** [comment]
I'm unclear what you want me to do? Figure out a way to get newer GCC installed on the older CentOS?

**Comment by hzeller** [comment]
Correct. I suspect there are backport channels of sorts that have newer compilers available. Since you wrangled these issues before, you might see quickly what needs to be done.

**Comment by mithro** [comment]
If the only problem is CentOS, then it is pretty easy. CentOS has these things called `devtoolset` -- see https://www.softwarecollections.org/en/scls/rhscl/devtoolset-8/ and the lines @ https://github.com/google/verible/blob/master/releasing/centos/6/bazel.dockerstage#L11 and https://github.com/google/verible/blob/master/releasing/centos/6/bazel.dockerstage#L25

**Comment by hzeller** [comment]
Also the Ubuntu Xenial and Bionic were affected https://github.com/google/verible/runs/2415978347

**Comment by mithro** [comment]
You need to update https://github.com/google/verible/blob/master/releasing/ubuntu/xenial/compiler.dockerstage and add the equivalent for Bionic.
